project:
  type: website
  output-dir: docs

website:
  page-footer: "Copyright 2025, Felipe Antonio Dzul Manzanilla | Fabián Correa-Morales"
  title: "Focos de Transmisión del Dengue"
  repo-url: https://github.com/fdzul/-dev
  repo-actions: [edit, issue]
  favicon: imagenes/logo.jpg
  twitter-card: true
  navbar:
    logo: imagenes/logo_course.jpeg
    tools:
      - icon: twitter
        href: https://twitter.com/FdzulM
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
    left:
      - href: index.qmd
        text: Objetivos
      - href: about.qmd
        text: Detalles
      - text: "Temario"
        href: temario.html
      - text: "Labs"
        href: Labs.html
      - text: "Referencias"
        href: links.html
      - text: "Contacto"
        href: contacto.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
margin-header: |
 ![](imagenes/logo.jpg)

